controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_about: 
    path: /about
    controller: App\Controller\HomeController::aboutBook